### ISSUE TITLE
Notion 'YYYY-MM-DD' Dates are saved as 'YYYY-MM-DDTHH:MM:SSZ' DateTimes 

### ISSUE THREAD

**Issue by gigena-git** [julien040/anyquery#26]
Hello again! These two bugs are related and I saw them after [this issue](https://github.com/julien040/anyquery/issues/25) was solved:
### Bug 1
When I try to update a date with:
```bash
anyquery -q "UPDATE notion_database SET \`Review Date\` = '2024-12-17' WHERE _page_id = '15776305-7c51-80db-ada0-f8cb0daa92cb';"
```
or with:
```bash
anyquery -q "UPDATE notion_database SET \`Review Date\` = '17/12/2024' WHERE _page_id = '15776305-7c51-80db-ada0-f8cb0daa92cb';"
```
Then, on the Notion UI I see that the "Include Time" flag set to true, and the time is `00:00:00` in the UTC timezone.

The expected result is that the new value for `Review Date` should be just a date with no time specified ("Include Time" set to false).
(PS: When I update a date with either `YYY-MM-DDTHH:MM:SSZ` or with `YYYY-MM-DDTHH:MM:SSZ/YYYY-MM-DDTHH:MM:SSZ` (with `Z` being any offset) the date time is saved correctly).

### Bug 2
Moreover, let's say that in my table I have more fields that are also date fields, and each of these fields contain a date (or two dates with or without time)  So, if I want to modify the `Title` field of the row, and I run this:
```bash
anyquery -q "UPDATE notion_database SET \`Title\` = 'New Name' WHERE \`_page_id\` = '15776305-7c51-80db-ada0-f8cb0daa92cb';"
```
Then, all date fields are ALSO modified like this:
- If the field had the "Include Time" flag set to false, it is now set to true and, the time is `00:00:00` in the UTC timezone.
- If the field had the "Include Time" flag set to true and the time zone was `Z`, then the field stays as is.
- If the field had the "Include Time" flag set to true and the time zone was not `Z`, then the field is still shown with the correct offset, but the time zone id is gone (from the UI).

The expected result is that any field that I'm not explicitly modifying in the `UPDATE` command should stay as it is.

**Comment by julien040** [comment]
Hello @gigena-git,
Thank you for opening an issue.

About the first bug, it's a known issue with the third-party library I'm using to connect to the Notion API [https://github.com/jomei/notionapi/issues/177](https://github.com/jomei/notionapi/issues/177). I can try to push for a pull request, but I can't guarantee anything.

About the second bug, I've fixed it in abbb833 and 527d410. It'll be available in the next anyquery version. I'll ping you when the version is released.

**Comment by julien040** [comment]
Hello @gigena-git,
Now, non-updated date fields should stay as they are. To get the fix, **update Anyquery to `0.3.1`** and **update the Notion plugin** with

```bash
anyquery registry refresh
anyquery plugin update notion
```

I'm still looking into fixing time zones and date-only fields. I can't give you an ETA, though, because it depends on the library maintainer.

**Comment by gigena-git** [comment]
Hello! Sorry for the delay.
I just tested the partial update and works fine! I'll let you know if I find anything else.
Happy holidays!

**Comment by julien040** [comment]
Hello @gigena-git ,
Sorry for the extremely delayed answer.

The secong bug should be fixed with the latest version of Anyquery. Make sure to update Anyquery (Winget, Brew, APT, etc. following your platform).
And then, update the Notion plugin `anyquery plugin update notion`

**Comment by gigena-git** [comment]
Hmm I thought that in [0.3.1](https://github.com/julien040/anyquery/issues/26#issuecomment-2558167027) the second bug was fixed, but now it was fixed again in [0.4.1](https://github.com/julien040/anyquery/issues/26#issuecomment-2738074661)?
Did something break in-between?

**Comment by julien040** [comment]
Sorry, I meant the first bug.
DateOnly should now stay date DateOnly, even after an update.

**Comment by gigena-git** [comment]
I tried from a fresh Anyquery install and the issue persists:
```bash
anyquery -q "UPDATE notion_database SET \`Review Date\` = '2025-03-20' WHERE _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';"
```

![Image](https://github.com/user-attachments/assets/8bb96081-7967-4d2d-94ab-d9725a4b3a7e)

Was the plugin updated in the server? I get this when running `anyquery plugins --json`:
```json
[
  {
    "author": "Julien040",
    "description": "Query your Notion database with SQL",
    "homepage": "https://github.com/julien040/anyquery/tree/main/plugins/notion",
    "library": 0,
    "name": "notion",
    "registry": "default",
    "tablename": [
      "database"
    ],
    "version": "0.1.4"
  }
]
```

**Comment by gigena-git** [comment]
Sorry for the delay. I was busy with other stuff. I've just finished giving a better look at the issue after the `0.4.1` release. These are the steps I took:

1. I put the date of the row I'm going to target to yesterday (3rd of July in my case):

<img width="222" height="86" alt="Image" src="https://github.com/user-attachments/assets/a3a2a9af-b96c-4a02-bdfd-417ce6f9123e" />

3. I downloaded the repo on branch `main` (commit `3c08194`)
4. I ran `make`.
5. I ran `./main.out plugin install notion`.
6. I then ran: 
```bash
./main.out -q "SELECT _page_id, \`Review Date\` from notion_database where _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';"
```
and I got:
```
+--------------------------------------+---------------------------+
|               _page_id               |        Review Date        |
+--------------------------------------+---------------------------+
| 1b076305-7c51-8059-97c6-f55d88a76ceb | 2025-07-03T00:00:00Z      |
+--------------------------------------+---------------------------+
```
4. Then I update:
```bash
./main.out -q "UPDATE notion_database SET \`Review Date\` = '2025-07-04' WHERE _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';"
```
and I got:

<img width="217" height="78" alt="Image" src="https://github.com/user-attachments/assets/31bd0d23-afb5-4ec1-9390-c31fd4fce2ad" />

### Some observations

What is really strange is that both the select and update operations do not seem to reflect the changes made in the [notion-anyquery-fork](https://github.com/julien040/notionapi-anyquery-fork/commit/10ee2306884b2610a17aecdcd87994a7b7367986) and [anyquery notion plugin](https://github.com/julien040/anyquery/commit/244285ca8d4f6c0345340fa3a5792f0eb9c9310b).

When I opened up the repo on Cursor and inspected [marshaling.go](https://github.com/julien040/anyquery/blob/main/plugins/notion/marshalling.go) the reference is correct and your fork is called instead of the main Notion Go client. However I was not able to run the application.

Is there any way to test the plugin while running the application in dev mode? So far I have not found a way to install a plugin from source, as every time I run the `plugin install` command, it always installs from the registry.

**Comment by gigena-git** [comment]
Thanks for the info! Now I've done the following:

1. Build anyquery with `make`.
2. Go to the `plugins/notion` folder, and place `devManifest.json` with the contents of the comment above.
3. Run `../../main.out --dev`.
4. Run: 
```sql
UPDATE notion_database SET `Review Date` = '2025-07-13' WHERE _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';
```
5. Check Notion: 
<img width="200" height="53" alt="Image" src="https://github.com/user-attachments/assets/9231788f-c1d2-4550-8eb3-7ef85346f6c2" />

6. Fetch the same row from anyquery
```sql
SELECT _page_id, `Review Date` from notion_dev_database where _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';
```
with result:
```
+--------------------------------------+-------------+
|               _page_id               | Review Date |
+--------------------------------------+-------------+
| 1b076305-7c51-8059-97c6-f55d88a76ceb | 2025-07-13  |
+--------------------------------------+-------------+
```

So, it seems that when loading the Notion plugin from source and not from the registry the issue no longer happens. Just to check I also tested double date updates:
```sql
UPDATE notion_dev_database SET `Review Date` = '2025-07-14/2025-07-15' WHERE _page_id = '1b076305-7c51-8059-97c6-f55d88a76ceb';
```
with result:

<img width="207" height="70" alt="Image" src="https://github.com/user-attachments/assets/20e7734d-f63d-44c2-a223-4bfec7e670fc" />

I haven't tested with times yet but I will do so in the coming days.

**Comment by julien040** [comment]
Hi @gigena-git, thank you for trying from the source.

I don't really understand why the source doesn't have the issue and works as expected. Maybe when I published the `0.1.4` version, I built the wrong version without the fix. Just in case, I've published a new version `0.1.5` that is the same as the source.

**Comment by gigena-git** [comment]
Hi @julien040 I've just tested a fresh install on an EC2 box. So, in version `0.1.5` of the Notion plugin, this issue no longer occurs. We can -finally! - close this.

Thanks for your time looking at this!
